version: "3"

services:
  pulsar:
    build: pulsar
    restart: always
    ports:
      - 8088:8088
      - 5678:5678
    networks:
      - app_network
    container_name: pulsar
    env_file:
      - .env
    volumes:
      - ./data:/data
      - ./backend:/fastapi

  # frontend:
  #   build: frontend
  #   restart: always
  #   depends_on:
  #     - backend
  #   ports:
  #     - 3000:3000
  #   networks:
  #     - app_network
  #   container_name: frontend
  #   env_file:
  #     - .env
  #   volumes:
  #     - ./data:/data
  #     - ./frontend:/app
  #     - /app/node_modules

networks:
  app_network:
    driver: bridge

# volumes:
#   data:
#     name: data
