version: "3"
services:
  pulsar:
    image: apachepulsar/pulsar:latest
    command: bin/pulsar standalone
    hostname: pulsar
    ports:
      - "8080:8080"
      - "6650:6650"
    restart: always
    volumes:
      - "./data/:/pulsar/data"
  dashboard:
    image: apachepulsar/pulsar-manager:v0.2.0
    ports:
      - "9527:9527"
      - "7750:7750"
    depends_on:
      - pulsar
    links:
      - pulsar
    environment:
      SPRING_CONFIGURATION_FILE: /pulsar-manager/pulsar-manager/application.properties


version: "3"

services:
  pulsar:
    build: pulsar
    restart: always
    ports:
      - 6650:6650
      - 8080:8080
    networks:
      - app_network
    container_name: pulsar
    env_file:
      - .env
    volumes:
      - pulsardata:/pulsar/data
      - pulsarconf:/pulsar/conf

  pulsar-manager:
    build: pulsar-manager
    restart: always
    ports:
      - 6650:6650
      - 8080:8080
    networks:
      - app_network
    container_name: pulsar-manager

  # frontend:
  #   build: frontend
  #   restart: always
  #   depends_on:
  #     - backend
  #   ports:
  #     - 3000:3000
  #   networks:
  #     - app_network
  #   container_name: frontend
  #   env_file:
  #     - .env
  #   volumes:
  #     - ./data:/data
  #     - ./frontend:/app
  #     - /app/node_modules

networks:
  app_network:
    driver: bridge

volumes:
  pulsardata:
    name: pulsardata
  pulsarconf:
    name: pulsarconf
